document_writer/document/urls.py
from django.urls import path
from .views import home_view, DocumentDetailView, new_view, delete_view

app_name = "document"

urlpatterns = [
    path('', home_view, name='home'),
    path('detail/<pk>/', DocumentDetailView.as_view(), name="detail"),
    path('new', new_view, name="new"),
    path('<id>/delete', delete_view, name="delete")
]

document_writer/document_writer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('document.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

document_writer/document/models.py
from django.db import models
from random import randint


# Create your models here.
from django.urls import reverse
# from fpdf import FPDF


class Document(models.Model):
    doc_name = models.CharField(verbose_name="document_name", default=f"Document{randint(1029283, 918829102832123)}",
                                max_length=250, blank=True, unique=True)
    doc = models.TextField(verbose_name="document", help_text="you cannot add an emoji")
    about = models.TextField(help_text="Write some description about the document", default="", blank=True)
    doc_img = models.ImageField(default="doc_image.png", verbose_name="document_img")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.doc_name} created on {self.created} updated on {self.updated}"

    def get_absolute_url(self):
        return reverse('document:detail', kwargs={'pk': self.pk})

document_writer/document/forms.py
from django import forms
from django.forms import ModelForm

from .models import Document


class DocumentForm(ModelForm):
    doc = forms.CharField(widget=forms.Textarea(attrs={'cols': 189, 'rows': 20}))

    class Meta:
        model = Document
        fields = '__all__'

document_writer/document/views.py
import os

from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from .models import Document
from django.views.generic import DetailView
from .forms import DocumentForm
from fpdf import FPDF


# Create your views here.
def home_view(request):
    return render(request, "home.html", {'document': Document.objects.all})


class DocumentDetailView(DetailView):
    model = Document
    template_name = 'detail.html'


def new_view(request):
    if request.method == "POST":
        form = DocumentForm(request.POST)
        if form.is_valid():
            doc = form.cleaned_data['doc']
            doc_name = form.cleaned_data['doc_name']
            about = form.cleaned_data['about']
            pdf = FPDF()
            pdf.add_page()
            pdf.set_font("Arial", size=15)
            pdf.cell(200, 10, txt=doc_name,
                     ln=1, align='C')
            pdf.cell(200, 20, txt=doc,
                     ln=2, align='C')
            pdf.cell(200, 10, txt=f"This is the about:{about}", ln=4, align='C')
            pdf.output(f"static/{doc_name}.pdf")
            form.save()
            return redirect("document:home")
    else:
        form = DocumentForm
    return render(request, "new.html", {'form': form})


def delete_view(request, id):
    # dictionary for initial data with
    # field names as keys
    context = {}

    # fetch the object related to passed id
    obj = get_object_or_404(Document, id=id)

    if request.method == "POST":
        # delete object
        os.remove(f'static/{obj.doc_name}.pdf')
        obj.delete()
        # after deleting redirect to
        # home page
        return HttpResponseRedirect("/")

    return render(request, "delete.html", context)

document_writer/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="static/style.css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>
</head>
<body>
{% block content %}{% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
</body>
</html>

document_writer/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block content %}
<div class="main">
    <!-- Create a Form -->
    <form method="POST" style="text-align:center;">
        <!-- Security token by Django -->
        {% csrf_token %}
        <h1>Do you want to Delete this Item ?</h1>
        <input type="submit" value="Yes" style="background-color:red;" />
        <a href="/" >Cancel </a>
    </form>
</div>
{% endblock content %}
</body>
</html>

document_writer/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{object.doc_name}}
{% endblock title %}

{% block content %}
<nav style="text-align:center;">
    <a href="{% url 'document:home' %}" class="link p-3">HOME🏠</a>
    <br>
    <a href="{% url 'document:new' %}" class="link p-3">NEW📂</a>
</nav>
<h1 style="text-align:center;" class="text-primary">{{object.doc_name}}</h1>
<h4>To download pdf go to http://127.0.0.1:8000/static/{{object.doc_name}}.pdf</h4>
<hr>
<h2 class="text-secondary">Created on {{object.created}} and last Updated on {{object.updated}}</h2>
<img src="/media/{{object.doc_img}}" alt="" width="50" height="50">
<h3 style="text-align:center">{{object.doc_name}}</h3>
<p style="text-align:center;">
    {{object.doc}}
</p>
<hr>
<h4>About</h4>
<b class="text-secondary" style="text-align:center;">{{object.about}}</b>
{% endblock content %}

document_writer/templates/home.html
{% extends 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}HOME PAGE{% endblock title%}</title>
</head>
<body>
{% block content %}
<h1 class="text-primary" style="text-align:center;">DOCUMENT WRITER</h1>
<h2>DOCUMENTS</h2>
<nav style="text-align:center;">
    <a href="{% url 'document:home' %}" class="link p-3">HOME🏠</a>
    <br>
    <a href="{% url 'document:new' %}" class="link p-3">NEW📂</a>
</nav>
<br>
{%for doc in document %}
<div class="card mb-3">
  <div class="card-body">
    <a class="card-link" href="{{doc.get_absolute_url}}">{{doc.doc_name}}</a>
    <p class="card-text">{{doc.about}}</p>
      <a href="{{doc.id}}/delete" class="btn btn-danger">DELETE</a>
    <p class="card-text"><small class="text-muted">Created on {{doc.created}}</small></p>
    <p class="card-text"><small class="text-muted">Last updated {{doc.updated}}</small></p>
  </div>
</div>
{%endfor%}
{% endblock content %}
</body>
</html>

document_writer/templates/new.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block title %}
NEW
{% endblock title %}

{% block content %}
<nav style="text-align:center;">
    <a href="{% url 'document:home' %}" class="link p-3">HOME🏠</a>
    <br>
    <a href="{% url 'document:new' %}" class="link p-3">NEW📂</a>
</nav>
<form action="" method="post" class="text-white">
    {% csrf_token %}
    <div class="row">
        <div class="col-6 m-3">
            {{ form.doc_name|as_crispy_field }}
        </div>
        <div class="col-6 m-3">
            {{ form.doc|as_crispy_field }}
        </div>
        <div class="col-6 m-3">
            {{ form.about|as_crispy_field }}
        </div>
        <div class="col-6 m-3">
            {{ form.doc_img|as_crispy_field }}
        </div>
    </div>
    <button class="text-white btn btn-dark m-3">CREATE</button>
</form>
{% endblock content %}